udemy/courses/urls.py
# SET THE NAMESPACE!
from . import views
from django.urls import path
app_name = 'courses'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('add-course/', views.create, name='add-course'),
    path('delete_course/<int:course_id>/', views.delete, name='delete_course'),
    path('update_course/<int:course_id>/', views.update, name='update_course'),
]

udemy/udemy/urls.py
from django.contrib import admin
from django.urls import path, include
from courses import views
urlpatterns = [
    path('', views.index, name='index'),
    path('special/', views.special, name='special'),
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('logout/', views.user_logout, name='logout'),
    
     #path('user_login/', views.user_login, name='user_login'),
]

udemy/templates/basic_apps/base _1.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Home</title>

    <style>
      body {
        overflow-x: hidden; /* Hide horizontal scrollbar */
      }

      /* Custom CSS to adjust container width */
      .container {
        max-width: 90%; /* Set the maximum width to the viewport width */
        padding-right: 15px;
        padding-left: 15px;
        margin-right: 15px;
        margin-left: 30px;
      }
    </style>

  </head>
  <body>
    {% include 'bacic_apps/nav.html' %}
    <div class="container">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

udemy/templates/basic_apps/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Udemy</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'courses:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'courses:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

udemy/templates/basic_apps/create_course.html
{% extends 'basic_apps/base.html' %}
{% block content %}
  <div class="my-4 col-md-4">
    <h2>Create Course</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Create</button>
      <a href="{% url 'index' %}" class="btn btn-secondary">Back</a>
    </form>
  </div>
{% endblock %}

udemy/templates/basic_apps/index.html
{% extends "partials/base.html" %}
{% block content %}

<table class="table table-bordered table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Course ID</th>
        <th scope="col">Title</th>
        <th scope="col">Subject</th>
        <th scope="col">Price</th>
        <th scope="col">Free</th>
        <th scope="col">Number of Subscribers</th>
        <th scope="col">Number of Reviews</th>
        <th scope="col">Number of Lectures</th>
        <th scope="col">Level</th>
        <th scope="col">Content Duration</th>
        <th scope="col">Published Date</th>
        <th scope="col">URL
        <th></th>
        </th>
      </tr>
    </thead>
    <tbody>
     {% for course in courses %}
     <tr>
        <td>{{course.course_id}}</td>
        <td>{{course.course_title}}</td>
        <td> {{course.subject.subject}}</td>
        <td> {{course.price.price}}</td>
        <td> {{course.is_paid}}</td>
        <td> {{course.num_subscribers}}</td>
        <td> {{course.num_reviews}}</td>
        <td> {{course.num_lectures}}</td>
        <td> {{course.level.level}}</td>
        <td> {{course.content_duration}}</td>
        <td> {{course.published_timestamp}}</td>
        <td> {{course.url}}</td>
        <td>
          <div class="btn-group">

            <form action="{% url 'courses:delete_course' course.course_id %}" method="POST">
                   {% csrf_token %}
            <button class="btn btn-outline-danger btn-sm mb-2" type="submit">Delete</button>
            </form>


           <form action="{% url 'courses:update_course' course.course_id %}" method="POST">
                {% csrf_token %}
                    {{ form.as_p }}
           <button type="submit" class="btn btn-sm btn-outline-secondary ml-2">Edit</button>
          </form>

          </div>


          </td>
     </tr>
     {% endfor %}
    </tbody>
  </table>

{% endblock %}

udemy/templates/basic_apps/login.html
{% extends 'basic_apps/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h3>Please Login</h3>

        <form method="post" action="{% url 'courses:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password">Password</label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

udemy/templates/basic_apps/nav.html
<style>
  .navbar .dropdown {
    margin-right: 0; /* Adjust the margin to bring dropdowns closer */
  }
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">UdemyCourses</a>
  <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'index' %}">
      {% csrf_token %}
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>


    <div class="dropdown">
      <button class="btn btn-outline-primary dropdown-toggle btn-sm" type="button" id="priceDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Price
      </button>
      <div class="dropdown-menu" aria-labelledby="priceDropdown">
        <form class="form-inline my-2 my-lg-0 p-2" method="GET" action="{% url 'index' %}">
          {% csrf_token %}
          <input class="form-control mr-sm-2 btn-sm" type="text" name="min_price" size="2" placeholder="Min" aria-label="Search">
          <span class="text-black mx-2">-</span>
          <input class="form-control mr-sm-2 btn-sm" type="text" name="max_price" size="2" placeholder="Max">
          <button class="btn btn-outline-success btn-sm ml-2" type="submit">Go</button>
        </form>
      </div>
    </div>

    <!-- Filter by Subscribers -->
    <div class="dropdown">
      <button class="btn btn-outline-primary dropdown-toggle btn-sm" type="button" id="subscribersDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Subscribers
      </button>
      <div class="dropdown-menu" aria-labelledby="subscribersDropdown">
        <form class="form-inline my-2 my-lg-0 p-2" method="GET" action="{% url 'index' %}">
          {% csrf_token %}
          <input class="form-control mr-sm-2 btn-sm" type="text" name="min_subs" size="2" placeholder="Min" aria-label="Search">
          <span class="text-black mx-2">-</span>
          <input class="form-control mr-sm-2 btn-sm" type="text" name="max_subs" size="2" placeholder="Max">
          <button class="btn btn-outline-success btn-sm ml-2" type="submit">Go</button>
        </form>
      </div>
    </div>

    <div class="dropdown">
      <button class="btn btn-outline-primary dropdown-toggle btn-sm" type="button" id="durationDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Duration
      </button>
      <div class="dropdown-menu" aria-labelledby="durationDropdown">
        <form class="form-inline my-2 my-lg-0 p-2" method="GET" action="{% url 'index' %}">
          {% csrf_token %}
          <input class="form-control mr-sm-2 btn-sm" type="text" name="min_cont" size="2" placeholder="Min" aria-label="Search">
          <span class="text-black mx-2">-</span>
          <input class="form-control mr-sm-2 btn-sm" type="text" name="max_cont"  size="2" placeholder="Max">
          <button class="btn btn-outline-success btn-sm ml-2" type="submit">Go</button>
        </form>
      </div>
    </div>

    <div class="dropdown">
      <button class="btn btn-outline-primary dropdown-toggle btn-sm" type="button" id="reviewsDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Reviews
      </button>
      <div class="dropdown-menu" aria-labelledby="reviewsDropdown">
        <form class="form-inline my-2 my-lg-0 p-2" method="GET" action="{% url 'index' %}">
          {% csrf_token %}
          <input class="form-control mr-sm-2 btn-sm" type="text" name="min_rev" size="2" placeholder="Min" aria-label="Search">
          <span class="text-black mx-2">-</span>
          <input class="form-control mr-sm-2 btn-sm" type="text" name="max_rev"  size="2" placeholder="Max">
          <button class="btn btn-outline-success btn-sm ml-2" type="submit">Go</button>
        </form>
      </div>
    </div>

    <div class="dropdown">
       <button class="btn btn-outline-primary dropdown-toggle btn-sm" type="button" id="lecturesDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Lectures
       </button>
       <div class="dropdown-menu" aria-labelledby="lecturesDropdown">
         <form class="form-inline my-2 my-lg-0 p-2" method="GET" action="{% url 'index' %}">
           <input class="form-control mr-sm-2 btn-sm" type="text" name="min_lec" size="2" placeholder="Min" aria-label="Search">
           <span class="text-black mx-2">-</span>
           <input class="form-control mr-sm-2 btn-sm" type="text" name="max_lec"  size="2" placeholder="Max">
           <button class="btn btn-outline-success btn-sm ml-2" type="submit">Go</button>
         </form>
       </div>
     </div>
    <!-- Add other filter forms similarly -->
    <!-- Filter by Duration -->
    <!-- Filter by Reviews -->
    <!-- Filter by Lectures -->

    <!-- Add Course button -->
    <a href="{% url 'courses:add-course' %}">
      <button type="button" class="btn btn-outline-secondary">Add Course</button>
    </a>
  </div>
</nav>
<br>
<br>

udemy/templates/basic_apps/register.html
{% extends 'base.html' %}

{% block content %}
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}

udemy/templates/basic_apps/registration.html
{% extends "basic_apps/base.html" %}


{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h3>Please Register Here</h3>
       <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

udemy/templates/basic_apps/update.html
{% extends 'partials/base.html' %}
{% block content %}

  <div class="my-4 col-md-4">
    <h2>Edit Course</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Update</button>
      <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}